# THIS FILE IS AUTOMATICALLY GENERATED. IT IS POINTLESS TO MODIFY IT

from setuptools import setup

try:
    with open('readme.rst') as f:
        long_description = f.read()
except FileNotFoundError:
    long_description = 'Unicorn powered and colored terminal applications' 

setup(
    name='unicorn-colors',
    version='0.0.0',
    packages=['unicorn'],
    url='https://github.com/ddorn/unicorn-colors',
    license='MIT',
    author='Diego Dorn',
    author_email='diego.dorn@free.fr',
    description='Unicorn powered and colored terminal applications',
    long_description=long_description,
    install_requires=[],
    include_package_data=True,
    
    keywords=''
)
